<a href="https://colab.research.google.com/github/marcelounb/Deep_learning_book_francois/blob/master/chap2_3_testing_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
array1 = np.array(
    [[1, 2],
     [3, 4],
     [5, -1]])

In [3]:
array1.shape

(3, 2)

In [0]:
array2 = np.array(
    [[10,10],
    [0, 0],
     [1, -4]])

In [5]:
array2.shape

(3, 2)

In [0]:
# Sum of both arrays element-wise
array3 = array1+array2

In [7]:
array3

array([[11, 12],
       [ 3,  4],
       [ 6, -5]])

In [0]:
# Implementing by hand Summing arrays element-wise
def naive_add(x, y):
  assert len(x.shape)==2
  assert x.shape == y.shape

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] += y[i,j]
  return x

In [9]:
array4 = naive_add(array1, array2)
array4

array([[11, 12],
       [ 3,  4],
       [ 6, -5]])

In [10]:
# Relu function
array5 = np.maximum(array3, 0)
array5

array([[11, 12],
       [ 3,  4],
       [ 6,  0]])

In [0]:
# Implementing by hand relu arrays element-wise
def naive_relu(x):
  assert len(x.shape)==2

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = max(x[i, j], 0)
  return x

In [13]:
array6 = naive_relu(array3)
array6

array([[11, 12],
       [ 3,  4],
       [ 6,  0]])

numpy dot operations

In [28]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [0]:
# [[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]

In [0]:
array10 = np.array([[0,1,2],
           [10,20,30],
           [100,200,300]
           ])

In [0]:
array20 = np.array([[3,4,5],
           [100,0,11],
           [15,100,2000]
           ])

In [31]:
array7 = np.dot(array10, array20)
array7

array([[   130,    200,   4011],
       [  2480,   3040,  60270],
       [ 24800,  30400, 602700]])

In [0]:
# array7 = ([[0*3+1*100+2*15, 0*4+1*0+2*100 ,0*5+1*11+2*2000 ],
#            [ 10*3+20*100+30*15, 10*4+20*0+30*100 , 10*5+20*11+30*2000 ]
#            [ 100*3+200*100+300*15, 100*4+200*0+300*100 , 100*5+200*11+300*2000 ]
# ])